YAML

name: daily

# Schedule to run every 6 hours:
on:
  schedule:
    - cron: "0 */6 * * *"  # Runs at the beginning of every 6th hour

permissions:
  contents: write  # Request write permissions to the repository

jobs:
  daily:
    runs-on: ubuntu-latest

    # Install dependencies
    steps:
      - uses: actions/checkout@v3  # Use a specific version for stable behavior
      - uses: actions/setup-python@v3  # Use a specific version for stable behavior
        with:
          python-version: "3.10"  # Specify the required Python version
      - run: pip install openai dotenv pathlib textwrap jupyter lxml pandas requests beautifulsoup4 playwright html5lib

    # Execute Jupyter notebooks
    - run: jupyter notebook GPTdf-bylanguage.ipynb --execute
    - run: jupyter notebook GPTdf-russian.ipynb --execute

    # Commit and push changes (optional)
    - name: Commit and push changes (if any)
      run: 
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || true
        git push origin main  
      # Push to main branch (replace with desired branch)
      env:
        SENTIMENT_ACCESS: ${{ secrets.SENTIMENT_ACCESS }}