name: daily
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "30 7 * * *"  #Runs at 7:30 am

permissions:
  contents: write
jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install all necessary packages
        run: pip install openai python-dotenv pathlib jupyter lxml pandas requests beautifulsoup4 playwright html5lib google-generativeai torch transformers sentencepiece

      # Execute Jupyter notebooks

      - name: Scraping today's data and create csvs for visualization
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: jupyter nbconvert --to notebook --execute "GPTdf-bylang_count_totals.ipynb" --stdout
      # - name: Adding today's data to larger csv
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: jupyter nbconvert --to notebook --execute "GPTdf-russian.ipynb" --stdout
      - name: Commit and push any changes
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
